### ISSUE TITLE
Examples cut to silence half way through

### ISSUE THREAD

**Issue by mxmilkiib** [ChenPaulYu/djtransgan-icassp2022#1]
I'm guessing they shouldn't do that?

**Comment by ChenPaulYu** [comment]
Hi, thanks for your questions. The padding silence is one of our preprocessing steps mentioned in section 2 and not the bug. However, I agree it is misleading and needs a clearer description.

> We consider audio segments of paired tracks (x1, x2), whose lengths have been made identical by zero-padding x1 at the back after Cout and zero-padding x2 at the front before Cin.

ps. Prev is x1, and Next is x2.

We add this zero-padding to let input audio have identical length and simplify the model's training process. 
I hope the explanation answers your question. If there is anything unclear, we can discuss it further.
